//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkShopPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public Orders()
        {
            this.CompletedWorks = new HashSet<CompletedWorks>();
            this.Payments = new HashSet<Payments>();
            this.UsedParts = new HashSet<UsedParts>();
        }
    
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int DeviceID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public int StatusID { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual ICollection<CompletedWorks> CompletedWorks { get; set; }
        public virtual Devices Devices { get; set; }
        public virtual Status Status { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual ICollection<UsedParts> UsedParts { get; set; }
    }
}
