//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkShopPC
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentMethods
    {
        public PaymentMethods()
        {
            this.Payments = new HashSet<Payments>();
        }
    
        public int ID { get; set; }
        public string PaymentMethodName { get; set; }
    
        public virtual ICollection<Payments> Payments { get; set; }
    }
}
